// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaU4cSvvF6mLIHzaM481hwQc3Bu4g720E',
    appId: '1:306036460104:web:815cdeaeeb2c8c83b8a67d',
    messagingSenderId: '306036460104',
    projectId: 'flutter-chitchat-app',
    authDomain: 'flutter-chitchat-app.firebaseapp.com',
    storageBucket: 'flutter-chitchat-app.appspot.com',
    measurementId: 'G-0V9Z282E5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsI3GZKXL0LvlhdUMQMrMFD_TXRtlnxgc',
    appId: '1:306036460104:android:93e716c25574a79cb8a67d',
    messagingSenderId: '306036460104',
    projectId: 'flutter-chitchat-app',
    storageBucket: 'flutter-chitchat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJh3tSpT0SiNVlHGwFEB5kqv3Pc0WwIY',
    appId: '1:306036460104:ios:dada158cb6c0cc1ab8a67d',
    messagingSenderId: '306036460104',
    projectId: 'flutter-chitchat-app',
    storageBucket: 'flutter-chitchat-app.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJh3tSpT0SiNVlHGwFEB5kqv3Pc0WwIY',
    appId: '1:306036460104:ios:99e0f786784b1759b8a67d',
    messagingSenderId: '306036460104',
    projectId: 'flutter-chitchat-app',
    storageBucket: 'flutter-chitchat-app.appspot.com',
    iosBundleId: 'com.example.chitchat.RunnerTests',
  );
}
